version: "3.0"

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - 9229:9229
    command: npm run start:dev
    # depends_on:
    #   - postgres
    restart: always

  # postgres:
  #   container_name: postgres
  #   image: postgres:15
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_PASSWORD: "admin123"
  #     PG_DATA: /var/lib/postgresql/data
  #   command: "-p ${POSTGRES_PORT}"
  #   ports:
  #     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "${PGADMIN_PORT}:${PGADMIN_PORT}"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
  #     PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONT_APP_PORT}:${FRONT_APP_PORT}"
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin-data:
